apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloha-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: alloha-backend
        image: python:3.11-slim
        command: ["sh", "-c"]
        args:
        - |
          pip install fastapi uvicorn requests &&
          cat > main.py << 'EOF'
          from fastapi import FastAPI, Request, HTTPException
          from fastapi.responses import PlainTextResponse
          import os
          import logging

          logging.basicConfig(level=logging.INFO)
          logger = logging.getLogger(__name__)

          app = FastAPI(title="Alloha WhatsApp Bot", description="AI-powered real estate WhatsApp bot", version="1.0.0")

          VERIFY_TOKEN = os.getenv("WHATSAPP_WEBHOOK_VERIFY_TOKEN", "alloha_secret")

          @app.get("/")
          async def root():
              return {"message": "Alloha WhatsApp Bot is running!"}

          @app.get("/health")
          async def health():
              return {"status": "healthy", "service": "alloha-bot"}

          @app.get("/webhook", response_class=PlainTextResponse)
          async def verify_webhook(request: Request):
              params = request.query_params
              logger.info(f"Webhook verification: {dict(params)}")
              
              mode = params.get("hub.mode")
              token = params.get("hub.verify_token")
              challenge = params.get("hub.challenge")
              
              if mode == "subscribe" and token == VERIFY_TOKEN:
                  logger.info(f"Verified with challenge: {challenge}")
                  return challenge
              else:
                  logger.error(f"Verification failed. Mode: {mode}, Token: {token}")
                  raise HTTPException(status_code=403, detail="Verification failed")

          @app.post("/webhook")
          async def webhook_handler(request: Request):
              try:
                  body = await request.json()
                  logger.info(f"Received webhook: {body}")
                  return {"status": "success"}
              except Exception as e:
                  logger.error(f"Error: {str(e)}")
                  raise HTTPException(status_code=500, detail=str(e))
          EOF
          uvicorn main:app --host 0.0.0.0 --port 8000
        ports:
        - containerPort: 8000
        env:
        - name: WHATSAPP_WEBHOOK_VERIFY_TOKEN
          value: "alloha_secret"
